version: '3.4'

services:
  infradb:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4  
  
  infra.api:
    image: ${DOCKER_REGISTRY-}infraapi
    build:
      context: .
      dockerfile: Services/Infra/Infra.API/Dockerfile

  dwhproxy.api:
    image: ${DOCKER_REGISTRY-}dwhproxyapi
    build:
      context: .
      dockerfile: Services/DWHProxy/DWHProxy.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:

